FROM alpine@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
# Change a few characters but ensure file length remains the same
RUN echo "HeXXo from the image" > testfile
# Force date modified to a known fixed value
RUN touch -mt 1806220000 testfile
CMD cat testfile
