version: 2
jobs:
  build:
    docker:
      - image: library/docker:17
    working_directory: /tmp/build
    environment:
      DIND_IMAGE: localhost/docker-delta-test
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          set -ex
          set -o pipefail
          sh ./test.sh
