FROM docker:29-dind@sha256:3f3c01aaaebf7cce837356b688b7c059a4749f10bd7660dec7c58fc454a283f0

RUN set -eux; apk add --no-cache \
	rsync \
	git \
	nodejs-lts \
	npm

WORKDIR /usr/src/app

COPY . /usr/src/app/
RUN npm install --unsafe-perm && npm cache clean --force
