FROM balenalib/intel-nuc-node:6

# Install Systemd
ENV container docker
RUN apt-get update && apt-get install -y --no-install-recommends \
		systemd-sysv \
	&& rm -rf /var/lib/apt/lists/*

# We never want these to run in a container
# Feel free to edit the list but this is the one we used
RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    sys-kernel-config.mount \

    display-manager.service \
    getty@.service \
    systemd-logind.service \
    systemd-remount-fs.service \

    getty.target \
    graphical.target

COPY test/systemd/entry.sh /usr/bin/entry.sh
COPY test/systemd/balena.service /etc/systemd/system/balena.service

RUN systemctl enable /etc/systemd/system/balena.service

STOPSIGNAL 37
ENTRYPOINT ["/usr/bin/entry.sh"]
ENV INITSYSTEM on

VOLUME /var/lib/docker

RUN apt-get update \
	&& apt-get install -y aufs-tools rsync iptables wget git \
	&& rm -rf /var/lib/apt/lists/*

ENV DOCKER_VERSION 1.11.2
RUN wget -q -O /tmp/docker-${DOCKER_VERSION}.tgz https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz \
	&& tar xvfz /tmp/docker-${DOCKER_VERSION}.tgz -C /tmp \
	&& cp -r /tmp/docker/* /usr/bin/ \
	&& rm -rf /tmp/docker \
	&& chmod +x /usr/bin/docker*

WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install --unsafe-perm  && npm cache clean

COPY . /usr/src/app

COPY test/services/ /etc/systemd/system/

ENV INITSYSTEM on

RUN systemctl enable docker
CMD docker info
