FROM docker:29-dind@sha256:7dcdfc4a20246236f558175182ccace1eb15a41bd3eb119dd2284f393498b7c1

RUN set -eux; apk add --no-cache \
	rsync \
	git \
	nodejs-lts \
	npm

WORKDIR /usr/src/app

COPY . /usr/src/app/
RUN npm install --unsafe-perm && npm cache clean --force
